[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
verbosity = 3

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 1000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/config/config.toml