edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 80
format_strings = true
format_macro_matchers = true
reorder_impl_items = true
condense_wildcard_suffixes = true
