[package]
name = "airdrop"
type = "bin"
authors = ["Noir ZK Airdrop Contributors"]
version = "0.1.0"
license = "MIT"

[dependencies]
keccak256 = { tag = "v0.1.3", git = "https://github.com/noir-lang/keccak256" }
